title: felipecvo
tagline: "felipecvo's blog and oss projects"
author:
  name: Felipe Cavalcante Vilella de Oliveira
  email: felipecvo@gmail.com
  github: felipecvo
  twitter: felipecvo
  linkedin: felipecvo
